#board_check_revision(FORMAT LETTER HIGHEST_REVISION M)
board_check_revision(FORMAT MAJOR.MINOR.PATCH HIGHEST_REVISION 4.99.99 EXACT)
#board_check_revision(FORMAT MAJOR.MINOR.PATCH DEFAULT_REVISION 0.15.1)
